In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('student_performance_updated_1000.csv')

In [4]:
data

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,Kenneth Murray,Male,85.0,20.0,NaN,1.0,High,72.0,0.8,80.0,True
996,4497.0,Amy Stout,Female,91.0,NaN,86.0,0.0,High,90.0,3.9,80.0,True
997,1886.0,NaN,Male,85.0,8.0,82.0,2.0,Low,68.0,0.4,54.0,False
998,7636.0,Joseph Sherman,Male,88.0,17.0,60.0,2.0,High,85.0,0.9,53.0,True
999,8021.0,Maria Walls,Female,88.0,10.0,90.0,1.0,Medium,NaN,2.4,94.0,True

In [7]:
import pandas as pd

# load dataset
data = pd.read_csv("student_performance_updated_1000.csv")

# remove unnecessary columns
data = data.drop(columns=[
    "StudentID",
    "Name",
    "Gender",
    "ExtracurricularActivities",
    "ParentalSupport"
])

# check result
print(data.head())

# save cleaned dataset
data.to_csv("cleaned_student_data.csv", index=False)

print("Columns removed successfully!")

   AttendanceRate  StudyHoursPerWeek  PreviousGrade  FinalGrade  Study Hours  \
0            85.0               15.0           78.0        80.0          4.8
1            90.0               20.0           85.0        87.0          2.2
2            78.0               10.0           65.0        68.0          4.6
3            92.0               25.0           90.0        92.0          2.9
4             NaN               18.0           82.0        85.0          4.1

   Attendance (%) Online Classes Taken
0            59.0                False
1            70.0                 True
2            92.0                False
3            96.0                False
4            97.0                 True
Columns removed successfully!

In [8]:
data.head()

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,85.0,15.0,78.0,80.0,4.8,59.0,False
1,90.0,20.0,85.0,87.0,2.2,70.0,True
2,78.0,10.0,65.0,68.0,4.6,92.0,False
3,92.0,25.0,90.0,92.0,2.9,96.0,False
4,NaN,18.0,82.0,85.0,4.1,97.0,True

In [10]:
data.shape

(1000, 7)

In [11]:
import pandas as pd

# load dataset
data = pd.read_csv("student_performance_updated_1000.csv")

# remove unnecessary columns
data = data.drop(columns=[
    "StudentID",
    "Name",
    "Gender",
    "ExtracurricularActivities",
    "ParentalSupport"
])

# remove rows with missing values
data = data.dropna()

# check cleaned data
print(data.head())

# save cleaned dataset
data.to_csv("cleaned_student_data.csv", index=False)

print("Dataset cleaned successfully!")

   AttendanceRate  StudyHoursPerWeek  PreviousGrade  FinalGrade  Study Hours  \
0            85.0               15.0           78.0        80.0          4.8
1            90.0               20.0           85.0        87.0          2.2
2            78.0               10.0           65.0        68.0          4.6
3            92.0               25.0           90.0        92.0          2.9
6            70.0                8.0           60.0        62.0          4.5

   Attendance (%) Online Classes Taken
0            59.0                False
1            70.0                 True
2            92.0                False
3            96.0                False
6            96.0                False
Dataset cleaned successfully!

In [12]:
data.head()

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,85.0,15.0,78.0,80.0,4.8,59.0,False
1,90.0,20.0,85.0,87.0,2.2,70.0,True
2,78.0,10.0,65.0,68.0,4.6,92.0,False
3,92.0,25.0,90.0,92.0,2.9,96.0,False
6,70.0,8.0,60.0,62.0,4.5,96.0,False

In [13]:
import pandas as pd

data = pd.read_csv("student_performance_updated_1000.csv")

# remove unused columns
data = data.drop(columns=[
    "StudentID",
    "Name",
    "Gender",
    "ExtracurricularActivities",
    "ParentalSupport",
    "Study Hours",
    "Attendance (%)"
])

# remove missing values
data = data.dropna()

# convert boolean to numeric
data["Online Classes Taken"] = data["Online Classes Taken"].astype(int)

# save cleaned dataset
data.to_csv("cleaned_student_data.csv", index=False)

print("Final dataset ready for ML!")

Final dataset ready for ML!

In [14]:
data.head()

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,FinalGrade,Online Classes Taken
0,85.0,15.0,78.0,80.0,0
1,90.0,20.0,85.0,87.0,1
2,78.0,10.0,65.0,68.0,0
3,92.0,25.0,90.0,92.0,0
6,70.0,8.0,60.0,62.0,0

In [15]:
data.to_csv("cleaned_student_data.csv", index=False)

In [16]:
data

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,FinalGrade,Online Classes Taken
0,85.0,15.0,78.0,80.0,0
1,90.0,20.0,85.0,87.0,1
2,78.0,10.0,65.0,68.0,0
3,92.0,25.0,90.0,92.0,0
6,70.0,8.0,60.0,62.0,0
...,...,...,...,...,...
992,91.0,15.0,90.0,68.0,0
993,90.0,25.0,60.0,87.0,0
994,78.0,20.0,60.0,62.0,0
997,85.0,8.0,82.0,68.0,0
998,88.0,17.0,60.0,85.0,1

In [17]:
data.head()

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,FinalGrade,Online Classes Taken
0,85.0,15.0,78.0,80.0,0
1,90.0,20.0,85.0,87.0,1
2,78.0,10.0,65.0,68.0,0
3,92.0,25.0,90.0,92.0,0
6,70.0,8.0,60.0,62.0,0

In [18]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

# Load dataset
data = pd.read_csv("cleaned_student_data.csv")

# Features
X = data[[
    "AttendanceRate",
    "StudyHoursPerWeek",
    "PreviousGrade",
    "Online Classes Taken"
]]

# Target
y = data["FinalGrade"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create model
model = LinearRegression()

# Train model
model.fit(X_train, y_train)

# Check accuracy
score = model.score(X_test, y_test)
print("Model Accuracy:", score)

# Save model
with open("model.pkl", "wb") as f:
    pickle.dump(model, f)

print("model.pkl created successfully!")

Model Accuracy: -0.014827982610033485
model.pkl created successfully!

In [19]:
data.head()

,AttendanceRate,StudyHoursPerWeek,PreviousGrade,FinalGrade,Online Classes Taken
0,85.0,15.0,78.0,80.0,0
1,90.0,20.0,85.0,87.0,1
2,78.0,10.0,65.0,68.0,0
3,92.0,25.0,90.0,92.0,0
4,70.0,8.0,60.0,62.0,0